FROM docker.elastic.co/logstash/logstash:7.13.0
USER root
ADD ./settings/ /usr/share/logstash/

#RUN ./bin/logstash-plugin install ./plugin/logstash-output-cassandra/logstash-output-cassandra-5.0.0.gem \
#    && rm -rf /usr/share/logstash/pipeline/logstash.conf 
